---
- name: Install and configure Xray tls.
  hosts: all
  become: true
  vars:
    xray_clients: 10
    xray_domain: "my.doma.in.com"
    letsencrypt_email: "admin@mail.me"
    xray_port: 443

  roles:
    - xray
