---
- name: Determine latest GitHub release (local).
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    url: "https://api.github.com/repos/XTLS/Xray-core/releases/latest"
    body_format: json
  register: _github_release
  until: _github_release.status == 200
  run_once: true
  retries: 5

- name: Set xray_version variable.
  ansible.builtin.set_fact:
    xray_version: "{{ _github_release.json.tag_name | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"

- name: Set xray_download_url variable.
  ansible.builtin.set_fact:
    xray_download_url: "https://github.com/XTLS/Xray-core/releases/download/v{{ xray_version }}/Xray-linux-64.zip"
